authorName: default
experimentName: benchmark_goal_tuning_test
maxExecDuration: 1000h
maxTrialNum: 3000  # 1000 [100 - ?]
searchSpacePath: Training/search_space_Soccer.json
useAnnotation: false
nniManagerIp: 0.0.0.0  # TODO

tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize

# assessor:
#  builtinAssessorName: Medianstop
#  classArgs:
#    optimize_mode: maximize

trainingServicePlatform: pai
trialConcurrency: 8
trial:
  command: pip3 install --user numpy torch torchvision pyro-ppl tensorboardX && pip3 install --user gym==0.12 lightgbm nni hdfs && pip3 install --user -e git+https://github.com/cycraig/gym-goal#egg=gym_goal && pip3 install --user -e git+https://github.com/cycraig/gym-platform#egg=gym_platform && apt-get update -y && apt-get install -y flex && apt install -y qt4-default && python3 run_benchmark_nni.py --env_name Goal-v0 --train_episodes 250000
  codeDir: .
  gpuNum: 1
  cpuNum: 3
  memoryMB: 32384
  image: /deepo:latest
  virtualCluster: debug
  nniManagerNFSMountPath: /data/data0/
  containerNFSMountPath: /data/
  paiStoragePlugin: teamwise_storage

paiConfig:  # TODO
  # userName: openmindstudio
  # passWord: Passq1w2e3r4
  # host: 10.151.40.179
